config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :data
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "data#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: %i[ show edit update destroy ]

  # GET /data or /data.json
  def index
    @q = Datum.ransack(params[:q])
    @people = @q.result(distinct: true)
  end

  # GET /data/1 or /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data or /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: "Datum was successfully created." }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1 or /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: "Datum was successfully updated." }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1 or /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: "Datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def datum_params
      params.require(:datum).permit(:question, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper

    def display_query_sql(people)
        tag.p('SQL:') + tag.code(people.to_sql)
      end

end

app/views/data/_form.html.erb
<%= form_with(model: datum) do |form| %>
  <% if datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
        <% datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_area :question %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_area :answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing Datum</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<%= search_form_for @q do |f| %>
 <form>
 <div class="container">
  <div class="row">
    <div class="form-group col-6">
      <%= f.label :question_cont, class:"form-label"%>
      <%= f.search_field :question_cont, class:"form-control "%>
    </div>
      <br/>
    <div class="form-group col-6">    
    <%= f.label :answer_cont ,class:"form-label"%>
    <%= f.search_field :answer_cont , class:"form-control "%>
         </div>

      <br/>
          <div class="form-group col-6">

    <%= f.label :question_and_answer_cont ,class:"form-label"%>
    <%= f.search_field :question_and_answer_cont , class:"form-control "%>
       </div>

    <br/>

    <div class="form-group col-6">

    <%= f.label :question_or_answer_cont ,class:"form-label"%>
    <%= f.search_field :question_or_answer_cont , class:"form-control "%>
       </div>

    <br/>
    <div class="form-group col-6">
    <%= f.label :question_or_answer_not_cont ,class:"form-label"%>
    <%= f.search_field :question_or_answer_not_cont , class:"form-control "%>
    </div>
    <br/>
       <div class="form-group col-6">
    <%= f.label :question_or_answer_lt_all ,class:"form-label"%>
    <%= f.search_field :question_or_answer_lt_all , class:"form-control "%>

    </div>


    <%# f.label :answer_start %>
    <%# f.search_field :answer_start %>

    <%# f.label :question_or_description_or_answer %>
    <%# f.search_field :question_or_description_or_answer %>
      <br/>
      <br/>
      
    <div class="form-group col-6">

  <%= f.submit %>
  </div>
  </div>
    </div>

</form>
<% end %>

<p id="notice"><%= notice %></p>

<div class="card text-white bg-dark">
  <div class="card-body">
<%= display_query_sql(@people) %>
</div>
</div>
<br>

<h1>Data</h1>

<table class="table">
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% if params.has_key?(:q) %>
    <% @people.each do |datum| %>
      <tr>
        <td><%= highlight(datum.question, params[:q][:question_cont])%></td>
        <td><%= highlight(datum.answer, params[:q][:answer_cont])%></td>
      </tr>
    <% end %>
<% else %>
      <% @people.each do |datum| %>
      <tr>
        <td><%= datum.question%></td>
        <td><%= datum.answer%></td>
      </tr>
    <% end %>

<% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Datum', new_datum_path %>

app/views/data/new.html.erb
<h1>New Datum</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @datum.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @datum.answer %>
</p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SvuHomeworkAir</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">SVU Homework</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-labe  l="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>          
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to  "Home", data_path , class: "nav-link" %>
                </li>
               <li class="nav-item">
                    <%= link_to  "Add ", new_datum_path , class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to  "admin ", rails_admin_path , class: "nav-link" %>
                </li>


 </ul>
                          </div>
          
        </nav>
    <div class="container">
        <p class="alert"><%= alert %></p>
 
    <%= yield %>
        <!-- Footer -->
<footer class="page-footer font-small py-1 bg-light text-white-50 mt-4">
    <div class="footer-copyright text-muted text-center py-3">SVU Homework S21 @2021    </div>
  </footer>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Cairo&display=swap" rel="stylesheet">

  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>